site_name: BMWi Forecasting Tool
site_url: https://example.com/

nav:
    - Home: index.md
    # How to add subpages 
    - About:
        - Tool: about.md
        - Team: team.md 

theme: readthedocs